logging:
  config: classpath:logback.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  datasource:
    url: jdbc:mysql://116.62.141.108/jabf_new?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 49.233.135.92
    port: 6379
    password: redis123456
    timeout: 1200
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle : 1 
        max-wait : -1 
mybatis:
  mapper-locations: mapper/**Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8005/oauth/token
      user-authorization-uri: http://localhost:8005/oauth/authorize
      client-id: app
      clientAuthenticationScheme: form
    resource:
      user-info-uri: http://localhost:8005/user/tokenUser
      prefer-token-info: false
  
